package Main;
import Ice.Ice;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class Game
{
	private Ice mapPieces;
	public void init()
	{
	}
	
	public void generateItems()
	{
	}
	
	public void generateMap()
	{
	}
	
	public void generateCharacters()
	{
	}
	
	public void randomizeStorm()
	{
	}
	
	public void winGame()
	{
	}
	
	public void loseGame()
	{
	}
}
