package Ice;

import Characters.Character;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HoleIce.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class HoleIce extends Ice
{
	public void addItem()
	{
	}

	@Override
	public void moveHere(Character c) throws Exception
	{
		addCharacter(c);
		getCharacter(0).fallInWater();
		
	}

	
}
