package Ice;

import Characters.Character;
import Item.Item;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HoleIce.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class HoleIce extends Ice
{
	/**
	 * Alapertelmezett konstruktor.
	 */
	public HoleIce()
	{
		System.out.println("--> HoleIce()");
		System.out.println("<--");
	}
	/**
	 *
	 * @param i
	 */
	public void addItem(Item i)
	{
		//ide elvileg nem kell kiírás
	}
	/**
	 * A paraméretben megadott karakter
	 * @param c
	 */
	@Override
	public void moveHere(Character c)
	{
		System.out.println("--> moveHere(c)");
		addCharacter(c);
		try
		{
			getCharacter(0).fallInWater();
		} catch (Exception e)
		{
		}

		System.out.println("<--");
	}

	
}
