package Ice;
import Characters.Character;
import Item.Item;
import Strategy.IglooStrategy;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ice.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public abstract class Ice
{
	private int snow;
	private int maxCharacters;
	private Character characters;
	private Ice neighbours;
	private Item items;
	private IglooStrategy iglooStrategy;
	public int getMaxCharacters()
	{
	}
	
	public void stormEffects()
	{
	}
	
	public int getSnow()
	{
	}
	
	public void incSnow()
	{
	}
	
	public void decSnow()
	{
	}
	
	public void setIglooStrategy(IglooStrategy is)
	{
	}
	
	public void addNeighbour(Ice i)
	{
	}
	
	public Ice getNeighbour(int d)
	{
	}
	
	public Character getCharacter(int i)
	{
	}
	
	public int getCharNum()
	{
	}
	
	public void addCharacter(Character c)
	{
	}
	
	public void removeCharacter(Character c)
	{
	}
	
	public Item getItem(int i)
	{
	}
	
	public void breakIce()
	{
	}
	
	public void addItem(Item i)
	{
	}
	
	public void removeItem(Item i)
	{
	}
	
	public abstract void moveHere(Character c);
	
	public void buildIgloo()
	{
	}
	
	public void destroyIgloo()
	{
	}
}
