package Ice;

import Characters.Character;
import Strategy.Igloo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StableIce.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class StableIce extends Ice
{
	
	public StableIce()
	{
		super();
		
	}
	public void buildIgloo()
	{
		Igloo ig = new Igloo();
		setIglooStrategy(ig);
		decSnow();
	}

	@Override
	public void moveHere(Character c) 
	{
		System.out.println("		-->addCharacter(c)");
		addCharacter(c);
		System.out.println("		<--");
	}
	
}
