package Ice;

import Characters.Character;
import Strategy.Igloo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StableIce.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class StableIce extends Ice
{
	
	public StableIce()
	{
		super();
		System.out.println("--> StableIce()");
		System.out.println("<--");
	}
	public void buildIgloo()
	{
		System.out.println("--> buildIgloo()");
		Igloo ig = new Igloo();
		setIglooStrategy(ig);
		decSnow();
		System.out.println("<--");
	}

	@Override
	public void moveHere(Character c) 
	{
		addCharacter(c);
	}
	
}
