package Ice;

import java.net.Socket;

import Characters.Character;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UnstableIce.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class UnstableIce extends Ice
{
	/**
	 * Egy parameteres konstruktor
	 * @param maxChar
	 */
	public UnstableIce(int maxChar)
	{
		super(maxChar, 0);
	}
	/**
	 * A karakter mozgasa hivja meg, ha sokan alnak rajta akkor meghivja a fallInWater-t
	 * @param c
	 */
	@Override
	public void moveHere(Character c) {

		addCharacter(c);
		c.setIce(this);
		if(getCharNum() >= getMaxCharacters())
			for (int i = getCharNum()-1; i>= 0; i--)
			{
				try
				{
					getCharacter(i).fallInWater();
				} catch (Exception e)
				{
					System.out.println(e);
				}
				
			}

	}
	
}
