package Ice;

import java.net.Socket;

import Characters.Character;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UnstableIce.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class UnstableIce extends Ice
{
	public UnstableIce(int maxChar)
	{
		super(maxChar);
	}

	@Override
	public void moveHere(Character c) {
		addCharacter(c);
		
		if(getCharNum() >= getMaxCharacters())
			for (int i = 0; i < getCharNum(); i++)
			{
				try
				{
					getCharacter(i).fallInWater();
				} catch (Exception e)
				{
					System.out.println(e);
				}
				
			}
	}
	
}
