package Ice;

import Characters.Character;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UnstableIce.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class UnstableIce extends Ice
{

	@Override
	public void moveHere(Character c) {
		// TODO Auto-generated method stub
		
	}
	
}
