package Strategy;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DigStrategy.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public interface DigStrategy
{
	public void dig(Character c);
}
