package Strategy;
import Characters.Character;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DigStrategy.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//



//Az ásás stratégiájának interfésze.
public interface DigStrategy 
{
	public void dig(Character c);
}
