package Strategy;
import Characters.Character;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DigStrategy.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//


/**
 * Az asas strategiajanak interfesze.
 */
public interface DigStrategy 
{
	/**
	 * Az asast megvalosito fuggveny deklaralasa.
	 * @param c : a karakter, aki as
	 */
	public void dig(Character c);
}
