package Strategy;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DivingSuitStrategy.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//

import Characters.*;


public class DivingSuitStrategy implements WaterStrategy
{
	//Mivel a karakteren van búvárruha, ezért kimászik a legelső található szomszéd mezőre.
	public void fallInWater(Character c)
	{
		c.move(0);
	}
}
