package Strategy;
import Characters.Character;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HelpStrategy.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//



//A segítségnyújtás stratégiája.
public interface HelpStrategy
{
	public boolean help(Characters.Character c1, Characters.Character character);
}
