package Strategy;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HelpStrategy.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public interface HelpStrategy
{
	public boolean help(Character c1, Character c2);
}
