package Strategy;

import Ice.Ice;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IglooStrategy.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public interface IglooStrategy
{
	public void stormEffects(Ice i);
	
}
