package Strategy;
import Characters.Character;
import Ice.*;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NoDivingSuit.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//


/**
 * Ez a strategia fut le, ha a vizbe esett karakteren nincs buvarruha.
 */
public class NoDivingSuit implements WaterStrategy
{
	/**
	 * Amig a karaktert nem menti meg valaki, vagy van meg szomszedja a lyuknak, amibe beleesett,
	 * 	addig vesszuk a kovetkezo szomszedot, megnezzuk, hogy hany karakter all rajta,
	 * 	es amig nem menti meg valaki vagy van meg karakter, addig a karakternek meghivjuk a help fuggvenyet,
	 * 	ami megadja, hogy megmentette-e a karaktert, vagy sem.
	 * 	Ha a karakterek és a szomszedok is elfogynak, es senki nem mentette meg, akkor meghal.
	 * @param c : a karakter, aki vizbe esett
	 * @throws Exception
	 */
	public void fallInWater(Character c) throws Exception
	{
		Ice hole = c.getIce();
		boolean isSaved = false;
		int num = 0;
		while (isSaved == false || num < hole.getNeighbourNum())
		{
			Ice neighbour = hole.getNeighbour(num);
			int charCount = neighbour.getCharNum();
			int currentChar = 0;
			while (isSaved == false || currentChar < charCount)
			{
				Character c2 = neighbour.getCharacter(currentChar);
				isSaved = c2.help(c);
				currentChar++;
			}
			num++;
		}
		if (isSaved == false)
		{
			c.die();
		}
	}
}
