package Strategy;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NoDivingSuit.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class NoDivingSuit implements WaterStrategy
{
	public void fallInWater(Character c)
	{
	}
}
