package Strategy;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NoDivingSuit.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//

import Character.*;
import Ice.*;


public class NoDivingSuit implements WaterStrategy
{
	public void fallInWater(Character c)
	{
		Ice hole = c.getIce();
		bool isSaved = false;
		int num = 0;
		while (isSaved == false || van még szomszéd)  //ide kell majd a szomszédok száma
		{

		}
	}
}
