package Strategy;

import Ice.Ice;
import Characters.*;
import Characters.Character;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NoIgloo.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//



/**
 * Az Ice-hoz tartozo strategia, akkor fut le, ha nincs rajta iglu.
 */
public class NoIgloo implements IglooStrategy
{
	/**
	 * Alapertelmezett konstruktor.
	 */
	public NoIgloo()
	{
		System.out.println("--> NoIgloo()");
		System.out.println("<--");
	}
	/**
	 * Mivel nincs iglu az adott mezon, igy no eggyel a ho mennyisege.
	 * Elkerjuk a mezon allo karakterek szamat, majd vegigiteralunk rajtuk, és mindegyiknek csokken a testhoje eggyel.
	 * @param i : a jegtabla, melyre erkezik a vihar
	 */
	public void stormEffects(Ice i) throws Exception
	{
		System.out.println("--> stormEffects(i)");
		i.incSnow();
		int charNum = i.getCharNum();
		for(int sz = 0; sz < charNum; sz++)
		{
			Character character = i.getCharacter(sz);
			character.warmthDec();
		}
		System.out.println("<--");
	}
}
