package Strategy;
import Characters.Character;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NoRopeHelp.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//


/**
 * Ez a strategia akkor fut le, ha a megkert karakternel nincs kotel.
 */
public class NoRopeHelp implements HelpStrategy
{
	/**
	 * Alapertelmezett konstruktor.
	 */
	public NoRopeHelp()
	{
		System.out.println("--> NoRopeHelp()");
		System.out.println("<--");
	}
	/**
	 * Mivel a karakter nem tud segiteni, ezert hamis erteket ad vissza.
	 * @param c1 : a karakter aki segitseget ker
	 * @param c2 : a karakter, akit megkertek, hogy segitsen
	 * @return : megmondja, hogy nem sikerult megmenteni
	 */
	public boolean help(Character c1, Character c2)
	{
		System.out.println("--> help(c1, c2)");
		System.out.println("<-- false");
		return false;
	}
}
