package Strategy;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NoShovelDig.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class NoShovelDig implements DigStrategy
{
	public void dig(Character c)
	{
	}
}
