package Strategy;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NoShovelDig.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//

import Ice.*;
import Characters.*;


public class NoShovelDig implements DigStrategy
{
	//A karakteren keresztül megkapjuk a mezőt,
	//amin áll, és ezen csökkentjük a hó mennyiségét.
	//Mivel nincs nála ásó, ezért csak eggyel.
	public void dig(Character c)
	{
		Ice ice = c.getIce();
		ice.decSnow();
		c.decAction();
	}
}
