package Strategy;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NoShovelDig.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//

import Ice.*;
import Characters.*;
import Characters.Character;

/**
 * Ez a strategia fut le, ha az asast vegzo karakternel nincs aso.
 */
public class NoShovelDig implements DigStrategy
{
	/**
	 * Alapertelmezett konstruktor.
	 */
	public NoShovelDig()
	{
		
	}
	/**
	 * A karakteren keresztul megkapjuk a mezot,
	 * 	amin all, es ezen csokkentjuk a ho mennyiseget.
	 * 	Mivel nincs nala aso, ezert csak eggyel.
	 * @param c : a karakter, aki as
	 */
	public void dig(Character c)
	{
		
		Ice ice = c.getIce();
		ice.decSnow();
		c.decAction();
		
	}
}
