package Strategy;
import Characters.Character;
import Ice.Ice;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RopeHelp.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//


/**
 * Ez a strategia akkor ervenyesul, ha a karakternel van kotel.
 */
public class RopeHelp implements HelpStrategy
{
	/**
	 * Alapertelmezett konstruktor.
	 */
	public RopeHelp()
	{
		System.out.println("--> RopeHelp()");
		System.out.println("<--");
	}

	/**
	 * Mivel van a szomszednal kotel, ezert a vizbe esett karakter atlep az o mezojere.
	 * 	A fuggveny pedig igazat ad vissza, mivel a karakter meg van mentve.
	 * @param c1 : a karakter, aki segitseget ker
	 * @param c2 : a karakter, akit megkertek, hogy segitsen
	 * @return : visszaadja, hogy sikerult megmenteni
	 */
	public boolean help(Character c1, Character c2)
	{
		System.out.println("--> help(c1, c2)");
		Ice neighbor = c2.getIce();
		c1.moveTo(neighbor);
		System.out.println("<-- true");
		return true;
	}
}
