package Strategy;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RopeHelp.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class RopeHelp implements HelpStrategy
{
	public boolean help(Character c1, Character c2)
	{
	}
}
