package Strategy;
import Characters.Character;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WaterStrategy.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//



//Annak a stratégiája, hogy mi fut le, ammikor egy karakter a vízbe esik.
public interface WaterStrategy
{
	public void fallInWater(Character c) throws Exception;
}
