package Strategy;
import Characters.Character;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WaterStrategy.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//


/**
 * A karakter vizbe esesenek interfesze.
 */
public interface WaterStrategy
{
	/**
	 * A fuggveny mely megmondja, mi tortenik vizbe eseskor.
	 * @param c : a karakter aki vizbe esik
	 * @throws Exception
	 */
	public void fallInWater(Character c) throws Exception;
}
