package Strategy;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WaterStrategy.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public interface WaterStrategy
{
	public void fallInWater(Character c);
}
