package Item;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cartridge.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class Cartridge extends Gun
{
    /**
     * Alapertelmezett konstruktor.
     */
    public Cartridge()
    {
        super(-1);
        System.out.println("--> Cartridge()");
        System.out.println("<--");
    }
}
