package Item;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Flare.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class Flare extends Gun
{
}
