package Item;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FlareGun.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class FlareGun extends Gun
{
    /**
     * Alapertelmezett konstruktor.
     */
    public FlareGun()
    {
        super();
        System.out.println("--> FlareGun()");
        System.out.println("<--");
    }
}
