package Item;

import Characters.Character;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Food.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//





public class Food extends Item
{
	/**
	 * Alapertelmezett konstruktor.
	 */
	public Food()
	{
		super();
	}
	/**
	 * A Food Item hasznalatat irja le. Ekkor meghivja a karakterenek a testho noveles fuggvenyet, majd eltavolitja magat tole.
	 */
	@Override
	public void use()
	{
		Character c = this.getCharacter();
		c.warmthInc();
		c.removeItem(this);
		c.decAction();
	}
	@Override
	public String getItemClass()
	{
		return "Food";
	}
	
}
