package Item;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gun.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//





public class Gun extends Item
{
	/**
	 * Alapertelmezett konstruktor.
	 */
	public Gun()
	{
		System.out.println("--> Gun()");
		System.out.println("<--");
	}
	/**
	 * Gun Item hasznalata. Direkt nem csinal semmit. 
	 */
	@Override
	public void use() {
		System.out.println("--> use()");
		// direkt nem csinal semmit
		System.out.println("<--");
	}

}
