package Item;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gun.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//





public class Gun extends Item
{
	/**
	 * Alapertelmezett konstruktor.
	 */
	public Gun()
	{
		System.out.println("--> Gun()");
		System.out.println("<--");
	}

	/**
	 * Az alkatresz kikerul a normal itemek kozul, es bekerul az alkatreszek tarolojaba.
	 */
	@Override
	public void use() {
		character.removeItem(this);
		character.addGunpart(this);
	}

	/**
	 * Az alkatresz kikerul az alkatresztarolobol, es vissza a sima itemek koze.
	 */
	public void discard(){
		character.removeGunpart(this);
		character.addItem(this);
	}

}
