package Item;
import Characters.Character;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public abstract class Item
{
	private boolean frozen;
	private Character character;
	public Character getCharacter()
	{
	}
	
	public void setCharacter(Character c)
	{
	}
	
	public void removeCharacter()
	{
	}
	
	public abstract void use();
	
	public boolean getFrozen()
	{
	}
	
	public void defrost()
	{
	}
	
	public abstract void discard();
}
