package Item;

import Characters.Character;
import Ice.Ice;
import Strategy.RopeHelp;
import Strategy.NoRopeHelp;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rope.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class Rope extends Item
{

	/**
	 * A Rope Item hasznalatat irja le. Atallitja a HelpStrategiajat arra, hogy van nala kotel. 
	 */
	@Override
	public void use() {
		RopeHelp rh = new RopeHelp();
		Character c = this.getCharacter();
		c.setHelpStrategy(rh);
		
	}

	/**
	 * A Rope Item eldobasat irja le. Azzal, hogy atallitja a HelpStategiajat arra, hogy nincsen nala kotel.
	 * Utana pedig a Jegtabla Itemjeihez hozzadaja, amin a karakter all es eltavolitja a karaktertol. 
	 */
	@Override
	public void discard() {
		NoRopeHelp nrh = new NoRopeHelp();
		Character c = this.getCharacter();
		c.setHelpStrategy(nrh);
		
		Ice i = c.getIce();
		i.addItem(this);
		this.removeCharacter();
	}
	
}
