package Item;

import Characters.Character;
import Ice.Ice;
import Strategy.ShovelDig;
import Strategy.NoShovelDig;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shovel.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class Shovel extends Item
{
	/**
	 * Alapertelmezett konstruktor.
	 */
	public Shovel()
	{
		super();
		System.out.println("--> Shovel()");
		System.out.println("<--");
	}
	/**
	 * A Shovel Item hasznalatat irja le. Azzal, hogy atallitja a karakter asasi startegiajat arra, hogy van nala aso. 
	 */
	@Override
	public void use()
	{
		System.out.println("--> use()");
		ShovelDig sd = new ShovelDig();
		Character c = this.getCharacter();
		c.setDigStrategy(sd);
		System.out.println("<--");
	}

	/**
	 * A Shovel Item eldobasat irja le. Azzal, hogy atallitja a karakter asasi startegiajat arra, hogy nincsen nala aso. 
	 * Utana pedig a Jegtabla Itemjeihez hozzadaja, amin a karakter all es eltavolitja a karaktertol.
	 */
	@Override
	public void discard()
	{
		System.out.println("--> discard()");
		NoShovelDig nsd = new NoShovelDig();
		Character c = this.getCharacter();
		c.setDigStrategy(nsd);	
		System.out.println("<--");
	}
}
