package Characters;
import Ice.Ice;
import Item.Gun;
import Item.Item;
import Strategy.DigStrategy;
import Strategy.HelpStrategy;
import Strategy.WaterStrategy;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Character.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public abstract class Character implements Movable
{
	private int bodywarmth;
	private int action;
	private Ice ice;
	private Item equipment;
	private HelpStrategy helpStrategy;
	private DigStrategy digStrategy;
	private WaterStrategy waterStrategy; //valamit 
	public Ice getIce()
	{
	}
	
	public int getAction()
	{
	}
	
	public void resetAction()
	{
	}
	
	public void decAction()
	{
	}
	
	public void dig()
	{
	}
	
	public void breakIce()
	{
	}
	
	public void itemPickup(int i)
	{
	}
	
	public void addItem(Item i)
	{
	}
	
	public void assembleGun(Gun g1, Gun g2, Gun g3)
	{
	}
	
	public void removeItem(Item i)
	{
	}
	
	public void itemDiscard(Item i)
	{
	}
	
	public void itemGive(Character c, Item it)
	{
	}
	
	public void moveTo(Ice i)
	{
	}
	
	public void setIce(Ice i)
	{
	}
	
	public void setHelpStrategy(HelpStrategy hs)
	{
	}
	
	public void setDigStrategy(DigStrategy ds)
	{
	}
	
	public void setWaterStrategy(WaterStrategy ws)
	{
	}
	
	public int getWarmth()
	{
	}
	
	public void warmup()
	{
	}
	
	public void warmthDec()
	{
	}
	
	public void warmthInc()
	{
	}
	
	public void move(int d)
	{
	}
	
	public boolean help(Character c1)
	{
	}
	
	public void fallInWater()
	{
	}
	
	public void die()
	{
	}
}
