package Characters;
import java.util.ArrayList;
import java.util.IntSummaryStatistics;


import Ice.Ice;
import Item.Gun;
import Item.Item;
import Main.Game;
import Strategy.DigStrategy;
import Strategy.HelpStrategy;
import Strategy.NoDivingSuit;
import Strategy.NoRopeHelp;
import Strategy.NoShovelDig;
import Strategy.WaterStrategy;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Character.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public abstract class Character implements Movable
{
	private int bodywarmth;
	private int action;
	private Ice ice;
	private ArrayList<Item> equipment;
	private HelpStrategy helpStrategy;
	private DigStrategy digStrategy;
	private WaterStrategy waterStrategy; 
	
	/**
	 * default konstruktora a Characternek
	 */
	public Character()
	{
		bodywarmth = 4;
		action = 4;
		equipment = new ArrayList<Item>();
		NoRopeHelp nrh = new NoRopeHelp();
		helpStrategy = nrh;
		NoShovelDig nsd = new NoShovelDig();
		digStrategy = nsd;
		NoDivingSuit nds = new NoDivingSuit();
		waterStrategy = nds;
	}
	/**
	 * Character konstruktora, ha mas a testho kezdeti erteke
	 * @param bodywarmth  testho erteke
	 */
	public Character(int bodywarmth)
	{
		this();
		this.bodywarmth = bodywarmth;
	}
	/**
	 * Character kostruktora 
	 * @param i  az Ice erteke ahol a Character kezd 
	 * @param bodywarmth  testho erteke
	 */
	public Character(Ice i, int bodywarmth)
	{
		this(bodywarmth);
		ice = i;
		i.addCharacter(this);
	}
	/**
	 * Getter az aktualis jegtablara
	 * @return  Visszaadja az aktualis jegtablat, amin a Character all 
	 */
	public Ice getIce()
	{
		System.out.println("--> getIce()");
		System.out.println("<-- i");
		return ice;
	}
	/**
	 * Getter a action ertekere
	 * @return  aktualis action szamaval ter vissza
	 */
	public int getAction()
	{
		System.out.println("--> getAction()");
		System.out.println("<-- " + action);
		return action;
	}
	/**
	 * visszaallitja alapertekre az action pontok szamat
	 */
	public void resetAction()
	{
		System.out.println("--> resetAction()");
		action = 4;
		System.out.println("<--");
	}
	/**
	 * csokkenti az action pontok szamat 
	 */
	public void decAction()
	{
		System.out.println("--> decAction()");
		action -=1;
		System.out.println("<--");
	}
	/**
	 * meghivja a karakterhet tartozo aktualis strategy-t
	 */
	public void dig()
	{
		System.out.println("--> dig()");
		digStrategy.dig(this);
		System.out.println("<--");
	}
	/**
	 * feltori a jegbe fagyott itemeket, ha a jegtablan nincs ho
	 */
	public void breakIce()
	{
		System.out.println("--> breakIce()");
		int snow = ice.getSnow();
		
		if(snow==0) 
			ice.breakIce();
		decAction();
		System.out.println("<--");
	}
	/**
	 * felesz i a hobol az i-dik itemet, amennyiben az nincs befagyva �s van m�g hely az equipmentben
	 * @param i  az item sorszama a mit fel akarunk venni
	 */
	public void itemPickup(int i)
	{
		System.out.println("--> itemPickup()");
		try {
		if(equipment.size()<=4 && ice.getItem(i).getFrozen()==false) {
			addItem(ice.getItem(i));
			ice.removeItem(ice.getItem(i));
				} 
			}catch (Exception e) {
				System.out.println(e.getMessage());
			}
		System.out.println("<--");
	}
	/**
	 * kozzaadja egy itemet egy karakterhez
	 * @param i  az item  amit hozz� akarunk adni 
	 */
	public void addItem(Item i)
	{
		System.out.println("--> addItem(i)");
		equipment.add(i);
		i.setCharacter(this);
		System.out.println("<--");
	}
	/**
	 * osszerakja a fegyver 3 alkatreszet, es megnyerik a jatekor, amennyiben mindenki ugyan azon a mezon van
	 * @param g1  a fegyver egyik alkatresze
	 * @param g2  a fegyver masik alkatresze
	 * @param g3  a fegyver harmadik alkatresze
	 */
	public void assembleGun(Gun g1, Gun g2, Gun g3)
	{
		System.out.println("--> assembleGun(g1, g2, g3)");
		System.out.println("<--");
	}
	/**
	 * eltavolit egy itemet a Character equipment-jebol
	 * @param i  az Item amit eltavolitunk
	 */
	public void removeItem(Item i)
	{
		System.out.println("--> removeItem(i)");
		i.discard();
		equipment.remove(i);
		System.out.println("<--");
	}
	/**
	 * az item jegre valo ledobasakor meghivodo fuggveny
	 * @param i az item a mit a jegre dobunk 
	 */
	public void itemDiscard(Item i)
	{
		System.out.println("--> itemDiscard(i)");
		ice.addItem(i);
		removeItem(i);
		System.out.println("<--");
	}
	/**
	 * Item-et adunk at egyik Characternek a masiktol
	 * @param c  A Character akinek az itemet atadjuk 
	 * @param i  Az Item amit atadunk
	 */
	public void itemGive(Character c, Item i)
	{
		System.out.println("--> itemGive(c, i)");
		removeItem(i);
		c.addItem(i);
		System.out.println("<--");
	}
	/**
	 * A Charactert atmozgatjuk egy masik jegteblara, szomszedossag vizsgalat nelkul 
	 * @param i  a Jegtabla, amire moztgatjuk 
	 */
	public void moveTo(Ice i)
	{
		System.out.println("--> moveTo(i)");
		ice.removeCharacter(this);
		i.addCharacter(this);
		setIce(i);
		System.out.println("<--");
	}
	/**
	 * Setter az akutalis jegtabla beallitasara 
	 * @param i  az jegtabla, amire athelyezzuk a Character-t 
	 */
	public void setIce(Ice i)
	{
		System.out.println("--> setIce(i)");
		ice = i;
		System.out.println("<--");
	}
	/**
	 * settet a helpstrategyre 
	 * @param hs  a helpstrategy uj allapota
	 */
	public void setHelpStrategy(HelpStrategy hs)
	{
		System.out.println("--> setHelpStrategy(hs)");
		helpStrategy = hs;
		System.out.println("<--");
	}
	/**
	 * settet a DigStrategy 
	 * @param ds  a DigStrategy uj allapota
	 */
	public void setDigStrategy(DigStrategy ds)
	{
		System.out.println("--> setDigStrategy(ds)");
		digStrategy = ds;
		System.out.println("<--");
	}
	/**
	 * settet a WaterStrategy 
	 * @param ws a WaterStrategy uj allapota
	 */
	public void setWaterStrategy(WaterStrategy ws)
	{
		System.out.println("--> setWaterStrategy(ws)");
		waterStrategy = ws;
		System.out.println("<--");
	}
	/**
	 * getter a bodywarmth-ra
	 * @return aktualis bodywarmth-ot adja vissza
	 */
	public int getWarmth()
	{
		System.out.println("--> getWarmth()");
		System.out.println("<-- " + bodywarmth);
		return bodywarmth;
	}
	/**
	 * getter az Itemre, ami a Characternel van
	 * @param i az item sorszama
	 * @return i-dik Item
	 */
	public Item getItem(int i)
	{
		return equipment.get(i);
	}
	/**
	 * 3 akcioert novel a bodywarmth-on egyet 
	 */
	
	public void warmup()
	{
		System.out.println("--> warmup()");
		for (int i = 0; i < 3; i++) {
			decAction();
		}
		warmthInc();
		System.out.println("<--");
	}
	/**
	 * csokkenti a bodywarmth erteket eggyel 
	 */
	public void warmthDec()
	{
		System.out.println("--> warmthDec()");
		bodywarmth -=1;
		if (bodywarmth == 0) {
			die();
		}
		System.out.println("<--");
	}
	/**
	 * noveli a bodywarmth erteket eggyel 
	 */
	public void warmthInc()
	{
		System.out.println("--> warmthInc()");
		bodywarmth +=1;
		System.out.println("<--");
	}
	/**
	 * a Character-t mozgatjuk a fugvennyel
	 * @param d  a mozgas iranyat hatarozza meg 
	 */
	public void move(int d)
	{
		System.out.println("--> move(" + d + ")");  //konkret szam kell majd ide
		try {
		
			ice.getNeighbour(d).moveHere(this);
			ice.removeCharacter(this);
			setIce(ice.getNeighbour(d));
			ice.bearHere();
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
		System.out.println("<--");
	}
	/**
	 * Characternek a helpstrategy-jet meghivja, ami eldonti hogy tud-e segiten a masik karakternek
	 * @param c1  Character aki segiteni akar
	 * @return  visszater hogy tud-e segiteni (true), vagy sem (false)
	 */
	public boolean help(Character c1)
	{
		System.out.println("--> help(c1)");
		boolean result = helpStrategy.help(c1, this);
		System.out.println("<--" + result);
		return result;
	}
	/**
	 * a Character viselkedese a waterstrategy alapjan 
	 * @throws Exception
	 */
	public void fallInWater() throws Exception
	{
		System.out.println("--> fallInWater()");
		waterStrategy.fallInWater(this);
		System.out.println("<--");
	}
	/**
	 * a Character meghal, es a jeteknak vege
	 */
	public void die()
	{
		System.out.println("--> die()");
		System.out.println("<--");
	}
	
	public void removeGunpart() {
		// TODO Auto-generated method stub

	}
	
	public void addGunpart() {
		//TODO
	}
	public ArrayList<Item> getEquipment(){
		return equipment;
	}
}
