package Characters;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Eskimo.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//

import Ice.Ice;

import java.util.jar.JarOutputStream;

public class Eskimo extends Character
{
	/**
	 * Alapertelmezett konstruktor.
	 */
	public Eskimo()
	{
		super(5);
		System.out.println("--> Eskimo()");
		System.out.println("<--");
	}
	/**
	 * Az Eskimo i parameterrel ellatott konstruktora
	 * @param i
	 */
	public Eskimo(Ice i)
	{
		super(i, 5);
		System.out.println("--> Eskimo(i)");
		System.out.println("<--");
	}
	/**
	 *Az Eskimo kepessege
	 */
	public void ability()
	{
		System.out.println("--> ability()");
		if (getIce().getSnow() > 0) {
			getIce().buildIgloo();			
		}
		System.out.println("<--");
	}
}
