package Characters;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Movable.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public interface Movable
{
	public void move(int d);
}
