package Characters;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Scientist.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//




public class Scientist extends Character
{
	/**
	 * Alapertelmezett konstruktor.
	 */
	public Scientist()
	{
		super(4);
		System.out.println("--> Scientist()");
		System.out.println("<--");
	}

	/**
	 *
	 * @param d
	 * @return
	 * @throws Exception
	 */
	public int ability(int d) throws Exception
	{
		System.out.println("--> ability()"); //ide majd valami random szám kell
		System.out.println("<-- "); //ide is visszatérési értéknek
		return getIce().getNeighbour(d).getMaxCharacters();
		
	}
}
