package Characters;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Scientist.java
//  @ Date : 2020-03-28
//  @ Author : 
//
//

import Ice.Ice;

public class Scientist extends Character
{
	/**
	 * Alapertelmezett konstruktor.
	 */
	public Scientist()
	{
		super(4);
		System.out.println("--> Scientist()");
		System.out.println("<--");
	}
	public Scientist(Ice i)
	{
		super(i, 4);
		System.out.println("--> Scientist(i)");
		System.out.println("<--");
	}

	/**
	 *
	 * @param d
	 * @return
	 * @throws Exception
	 */
	public int ability(int d) throws Exception
	{
		System.out.println("--> ability(" + d + ")"); //ide majd valami random szám kell
		int result = getIce().getNeighbour(d).getMaxCharacters();
		System.out.println("<-- "+ result); //ide is visszatérési értéknek
		return result;
		
	}
}
